# Site settings
title: Praveen Kumar
description: Jekyll Theme Minimal Resume # http://willianjusten.com.br
#baseurl: "/portfolio_website" # the subpath of your site, e.g. /blog
#url: "rhapsodyai.github.io"

# User settings
username: Praveen Kumar
user_description: I'm a Java developer who has worked primarily with Java on Spring and Hiberbates. I have 1 years of experience in the tech industry, mostly working with small startups (not including my own). 
user_title: Software Engineer
email: praveenkumar.saggam@gmail.com
twitter_username: praveensaggam
github_username:  praveenspk


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
