# Site settings
title: Praveen Kumar
description: Jekyll Theme Minimal Resume # http://willianjusten.com.br
#baseurl: "/portfolio_website" # the subpath of your site, e.g. /blog
#url: "praveenspk.github.io"

# User settings
username: Praveen Kumar
user_description: I'm a Java developer who has worked primarily with Java on Spring ,SpringBoot, Hiberbates and Webservices(SOAP and REST). Having around 4 years of experience in the tech industry, currenttly I am working with <a href="https://www.capgemini.com/in-en/?georedirect_none=true">Capgemini technology Services India Ltd</a>. Previously worked for <a href="https://www.huawei.com/en/">Huawei Technologies India Pvt.Ltd.</a> 
user_title: Software Engineer
email: praveenkumar.saggam@gmail.com
twitter_username: praveensaggam
github_username:  Praveenspk


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
